export { default as Header } from './Header/Header'
export { default as SearchInput } from './SearchInput/SearchInput'
export { default as Profile } from './Profile/Profile'
export { default as Modal } from './Modal/Modal'
export { default as SideNav } from './SideNav/SideNav'
